### ISSUE TITLE
getStrongsEntry returns empty object on Android

### ISSUE THREAD

**Issue by zhuiks** [ezra-bible-app/node-sword-interface#19]
While working on showing dictionary info on long press and testing it on Android, I found that `ipcNsi.getStrongsEntry(normalizedKey)` returns an empty object in `dictionary_controller.js#143`
 https://github.com/ezra-project/ezra-project/commit/33018aa6f570d73aa642d987cd11b257a7f90176

Empty object will cause other errors. 

In Electron everything works fine

**Comment by tobias-klein** [comment]
Thanks for reporting this. Note that this is likely due to differences in the IPC communication and therefore probably not an issue in node-sword-interface, but rather how it is wrapped in the Cordova context.

**Comment by tobias-klein** [comment]
There is not much special about the method `getStrongsEntry`. How did you test this? In the Android emulator? Are the Strong's modules installed? That's the requirement for this to work.

**Comment by zhuiks** [comment]
Yes, it was on Emulator. Let me double-check about Strong's modules.

**Comment by tobias-klein** [comment]
Does the module assistant still automatically install the Strong's modules if a Bible translation has that feature? If not then that could be the root cause for this behavior.

**Comment by zhuiks** [comment]
I'm confirming that this is related to not having Strong's modules installed.
I created an issue: https://github.com/ezra-bible-app/ezra-bible-app/issues/404
