### ISSUE TITLE
minor documentation update needed for getAllRepoModules

### ISSUE THREAD

**Issue by shev72** [ezra-bible-app/node-sword-interface#36]
var repo="Xiphos";
    var modules=interface.getAllRepoModules(repo);
    for (var i = 0; i < modules.length; i++) {
        console.log( 'moduleName :  '  + JSON.stringify(modules[i])  + '\n');
    }

It seems in the code excertp above getAllRepoModules is returning an array of objects, not of strings (as in the current doc)

**Comment by tobias-klein** [comment]
Thank you @shev72. Yes, the API documentation needs an update for this.
