### ISSUE TITLE
refreshRemoteSourceConfiguration returning with -1

### ISSUE THREAD

**Issue by tobias-klein** [ezra-bible-app/node-sword-interface#37]
reported by @rockymartin0124

I executed the command "node examples/install_kjv.js" again, and got the scripts like this.

Updating repository configuration ...

refreshRemoteSourceConfiguration returned -1
Installing King James module
getModuleRepo: Got 0 repository names!
Could not find repository for module KJV
(node:8308) UnhandledPromiseRejectionWarning: -1
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8308) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8308) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Please explain about this.

_Originally posted by @rockymartin0124 in https://github.com/ezra-bible-app/node-sword-interface/issues/35#issuecomment-1366663718_

**Comment by tobias-klein** [comment]
@rockymartin0124
I created a separate issue for this topic, because it is independent of the other issue #35 you reported.

Could you try to go with https://github.com/ezra-bible-app/ezra-bible-app/issues/155#issuecomment-750302401 as mentioned in the other issue.

If the file `C:\Users\<your-user-name>\AppData\Roaming\sword\installMgr\InstallMgr.conf` is not existing please create it and add this section:

```
[General]
TimeoutMillis=20000
```

If the error keeps happening - please gradually increase the timeout to higher values (like 30000, 40000, ...).

**Comment by rockymartin0124** [comment]
I have made the file "InstallMgr.conf", and added the TimeoutMillis.
And I also increased the timeout to higher values, but the result is same.

**Comment by tobias-klein** [comment]
Ok.
Have you been using any other SWORD based software like Xiphos, BibleTime or Ezra Bible App and does the module installation work there?

**Comment by tobias-klein** [comment]
@rockymartin0124 
Let's try to get a full debug log of the command. To do that please execute the following commands in your node-sword-interface directory.

```cmd
set SWORD_LOGLEVEL=DEBUG
node examples\install_kjv.js > debuglog.txt 2>&1
```

Then please attach the file debuglog.txt to this issue (drag and drop the file into the issue comment editor).

The debug logfile will allow me to further analyze what's going wrong on your system.

**Comment by tobias-klein** [comment]
@rockymartin0124 Happy new year! Any additional feedback regarding this?

**Comment by rockymartin0124** [comment]
Happy New Year!
I have solved the problems.
Thanks.
I really give appreciates to your kind feedback and service.
If you have any job to do with anyone, please let me work with you together.
I really hope to work with a responsible developer like you.
Thanks again and regards...

**Comment by tobias-klein** [comment]
Glad to hear that it's working now. Can you provide additional hints, what did you change compared to previous attempts? I am curious.

**Comment by rockymartin0124** [comment]
@tobias-klein
I have already run node-sword-interface on Linux.
But now I MUST run it on Windows.
So I have tried the command "node example/install_kjv.js", but I have got the error, too.
So I tried 
`set SWORD_LOGLEVEL=DEBUG
node examples\install_kjv.js > debuglog.txt 2>&1`
I attach the debuglog.txt.
What should I do to solve this issue?
[debuglog.txt](https://github.com/ezra-bible-app/node-sword-interface/files/10353769/debuglog.txt)

**Comment by tobias-klein** [comment]
Hi @rockymartin0124 ,
Thanks. The logfile does not contain the debug information.
Could you run the two commands `set SWORD_LOGLEVEL=DEBUG` and
`node examples\install_kjv.js > debuglog.txt 2>&1` separately? I believe the environment variable was not set correctly when you executed both in one line.

**Comment by rockymartin0124** [comment]
Thanks for your reply @tobias-klein 
I have executed both separately.
After I received your reply, I tried again, but the result is the same.

The content of the file is like this:
`Updating repository configuration ...

refreshRemoteSourceConfiguration returned -1
Installing King James module
getModuleRepo: Got 0 repository names!
Could not find repository for module KJV
(node:22512) UnhandledPromiseRejectionWarning: -1
(Use `node --trace-warnings ...` to show where the warning was created)
(node:22512) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22512) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
[debuglog.txt](https://github.com/ezra-bible-app/node-sword-interface/files/10354574/debuglog.txt)

**Comment by tobias-klein** [comment]
Hi @rockymartin0124

If there is nothing else in the logfile, then the environment variable SWORD_LOGLEVEL=DEBUG must be set incorrectly.
I cannot further look into this without detailed info in the logfile.

Can you tell me more about your execution environment.
Did you use powershell or the cmd shell?
I just checked and found that the environment variable setting only works like this in the CMD shell. So in case you are using powershell that could explain why you did not get detailed debug information.

Please run these commands in a CMD window once more and provide the logfile again.

**Comment by rockymartin0124** [comment]
Hi @tobias-klein 
I have executed with cmd shell.
How can I check whether the environment variable SWORD_LOGLEVEL is DEBUG or not?

I tried again with CMD shell, but the result is same.
Could you give me the communication information like Skype, Telegram or Discord to communicate quickly?
If you can't, how about to access my pc by anydesk and look at my situation?

**Comment by tobias-klein** [comment]
On CMD, you can check the value of the environment variable by typing `echo %SWORD_LOGLEVEL%`.

We could have a look jointly, I'll contact you via email.

**Comment by rockymartin0124** [comment]
I executed `echo %SWORD_LOGLEVEL%`.
The result is DEBUG.

**Comment by tobias-klein** [comment]
What is your `Windows` version and what is your `node` version?

**Comment by rockymartin0124** [comment]
Windows10 (64bit)
node version is v14.21.2

**Comment by tobias-klein** [comment]
Are you using the 32-bit version of node?

**Comment by rockymartin0124** [comment]
Sure

**Comment by tobias-klein** [comment]
Ok. Let's handle further communication via email.
